version = 0.1
[default.deploy.parameters]
stack_name = "eu-procurement-twitter-bot"
resolve_s3 = true
s3_prefix = "eu-procurement-twitter-bot"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
